apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount.indexerd }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: aws-registry
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/app/indexerd"]
          volumeMounts:
            - name: configmap
              mountPath: /app/env.yaml
              subPath: env.yaml
            - name: logs
              mountPath: {{ .Values.logPath }}
        - name: filebeat
          image: elastic/filebeat:7.17.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: logs
              mountPath: {{ .Values.logPath }}
            - name: configmap
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
      volumes:
        - name: configmap
          configMap:
            name: {{ .Release.Name }}
        - name:  logs
          emptyDir: {}