image:
  repository: 981130112916.dkr.ecr.us-east-1.amazonaws.com/zildexr/zilliqa-chain
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

nameOverride: ""
fullnameOverride: ""

resources:
  requests:
    cpu: 0
    memory: 0M
  limits:
    cpu: 0.1
    memory: 1024M
