image:
  repository: 465700395685.dkr.ecr.eu-west-1.amazonaws.com/indexer/indexer
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

nameOverride: ""
fullnameOverride: ""

resources:
  requests:
    cpu: 0.1
    memory: 128M
  limits:
    cpu: 0.1
    memory: 512M
