name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        required:    true
        description: Which environment to deploy?
        type:        choice
        options:
          - testnet
          - mainnet
      tag:
        required:    true
        description: ECR tag
        default:     latest

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          repository: ZilDuck/automation
          ref:        master
          token:      ${{ secrets.ACCESS_TOKEN }}

      - name: Setup Helm Chart
        run: |
          mv /home/runner/work/zilliqa-chain-indexer/automation/deployments/zildexr/indexer .

      - name: Deploy Indexer
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --install indexer ./indexer/indexer -f ./indexer/config/${{ github.event.inputs.environment }}.yaml --namespace zildexr-${{ github.event.inputs.environment }}  --atomic --set=image.tag=${{ github.event.inputs.tag }}
          kubeconfig: '${{ secrets.KUBECONFIG }}'

      - name: Deploy Asset Server
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --install assets ./indexer/assets -f ./indexer/config/${{ github.event.inputs.environment }}.yaml --namespace zildexr-${{ github.event.inputs.environment }}  --atomic --set=image.tag=${{ github.event.inputs.tag }}
          kubeconfig: '${{ secrets.KUBECONFIG }}'

      - name: Deploy Metadata
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --install metadata ./indexer/metadata -f ./indexer/config/${{ github.event.inputs.environment }}.yaml --namespace zildexr-${{ github.event.inputs.environment }}  --atomic --set=image.tag=${{ github.event.inputs.tag }}
          kubeconfig: '${{ secrets.KUBECONFIG }}'
