name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        required:    true
        description: Which environment to deploy?
        type:        choice
        options:
          - testnet
          - mainnet
      tag:
        required:    true
        description: ECR tag
        default:     latest
env:
  APP: zildexr

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Deploy Assets to Kubernetes
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --install assets .helm/assets -f .helm/config/${{ github.event.inputs.environment }}.yaml --namespace ${{ env.APP }}-${{ github.event.inputs.environment }} --atomic --set=image.app.tag=${{ github.event.inputs.tag }}
          kubeconfig: '${{ secrets.KUBECONFIG }}'

      - name: Deploy indexer to Kubernetes
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --install indexer .helm/indexer -f .helm/config/${{ github.event.inputs.environment }}.yaml --namespace ${{ env.APP }}-${{ github.event.inputs.environment }} --atomic --set=image.app.tag=${{ github.event.inputs.tag }}
          kubeconfig: '${{ secrets.KUBECONFIG }}'

      - name: Deploy metadata to Kubernetes
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --install metadata .helm/metadata -f .helm/config/${{ github.event.inputs.environment }}.yaml --namespace ${{ env.APP }}-${{ github.event.inputs.environment }} --atomic --set=image.app.tag=${{ github.event.inputs.tag }}
          kubeconfig: '${{ secrets.KUBECONFIG }}'
